apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vm51u1zew-nodejs
  janus-idp.io/tekton: vm51u1zew-nodejs
  backstage.io/kubernetes-id: vm51u1zew-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vm51u1zew-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
